----
## 실습 문제
NumPy를 사용하여 다음과 같은 배열을 생성해 보세요.

1. 크기가 4x3인 모든 값이 0인 배열
2. 크기가 3x3인 모든 값이 1인 배열
3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
4. 0과 1 사이의 4개의 등간격 값을 가진 배열
5. 크기가 2x2인 정규 분포로 구성된 배열

In [2]:
!pip install numpy

In [5]:
import numpy as np

In [4]:
arr = np.zeros([4, 3])
print(arr)

arr = np.ones([3, 3])
print(arr)

arr = np.arange(0, 21, 5)
print(arr)

arr = np.linspace(0, 1, 4)
print(arr)

arr = np.random.randn(2, 2)
print(arr)

# 번외
arr = np.random.normal(loc=0, scale=1, size=(2, 2)) # 평균, 표준편차, 배열의 사이즈
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 0  5 10 15 20]
[0.         0.33333333 0.66666667 1.        ]
[[-0.87950956 -0.66427316]
 [-0.14574988  0.61234709]]
[[ 0.88798486 -1.01442659]
 [-0.31221638 -0.15122474]]


---
### 2 실습

In [16]:
# Q1
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)

print(arr[1, 2])
print(arr[:, :1])
print(arr[:2, :2])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
60
[[10]
 [40]
 [70]]
[[10 20]
 [40 50]]


In [21]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr)

print(arr[[0, 2, 4]])
print(arr[arr > 50])


[10 20 30 40 50 60 70]
[10 30 50]
[60 70]
