---
### 1 실습

In [4]:
!pip install numpy
import numpy as np

In [5]:
arr_1 = np.array([200, 340, 150, 400])
arr_2 = np.array([220, 300, 180, 420])

print(np.add(arr_1, arr_2))
print((np.add(arr_1, arr_2)) / 2) # 평균값 어떻게? 다 더하고 분기수 나누기?

[420 640 330 820]
[210. 320. 165. 410.]


In [6]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.divide(arr1, arr2))

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


---

### 2 실습

In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.dot(arr1, arr2))

32


In [8]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])
print(arr2d + arr1d)


[[11 22 33]
 [14 25 36]]


---
### 3 실습

In [11]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 20])
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))

[30 40 50]
150
50
10
30.0
