---
### ndarray 기본 연산

In [9]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
# 2차원 배열 연산
arr_a = np.arange(1, 10).reshape(3, 3) # .reshape() N차원의 모습으로 만들어 줌
arr_b = np.full_like(arr_a, 3) # .full_like(변수, 특정값) 차원이 있는 '변수'와 같은 모양으로 '특정값'으로 요소를 채워줌

print(arr_a)
print(arr_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [5]:
# 덧셈
print(arr_a + arr_b)
print(np.add(arr_a, arr_b))

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
# 뺄셈
print(arr_a - arr_b)
print(np.subtract(arr_a, arr_b))

[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]


In [7]:
# 곱셈
print(arr_a * arr_b)
print(np.multiply(arr_a, arr_b))

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [8]:
# 나눗셈
print(arr_a / arr_b)
print(np.divide(arr_a, arr_b))

[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]
[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]


In [9]:
# 특수연산1 : 거듭제곱
print(arr_a ** arr_b)
print(np.power(arr_a, arr_b))  # 거듭제곱
print(np.square(arr_a, arr_b)) # 제곱

[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]
[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [10]:
# 특수연산2: 몫
print(arr_a // arr_b)
print(np.floor_divide(arr_a, arr_b))

[[1 0 0]
 [0 0 0]
 [0 0 0]]
[[1 0 0]
 [0 0 0]
 [0 0 0]]


In [11]:
# 특수연산3: 나머지
print(arr_a % arr_b)
print(np.mod(arr_a, arr_b))

[[0 2 3]
 [4 5 6]
 [7 8 9]]
[[0 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# 제곱근
print(np.sqrt(arr_a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


---
### broadcasting 연산
- 두 배열의 shape이 다르면 broadcasting 연산을 수행한다.
- shape이 작은 쪽이 큰 쪽에 맞춰 확장한다.
- 두 배열의 행 또는 열이 일치해야 확장 가능하다.
- 크기가 1인 경우 무조건 확장 가능하다.
- shape이 다른 경우 마지막 축부터 차원이 동일한지 비교한다.

In [13]:
# arr_a = np.arange(1, 10).reshape(3, 3)
result_arr = arr_a * np.array([[5, 5, 5], [5, 5, 5], [5, 5, 5]]) # (3, 3)
result_arr = arr_a * np.array([5, 5, 5]) # (3,)
result_arr = arr_a * np.array([5]) # (1,)
result_arr = arr_a * 5 # 스칼라값

print(result_arr)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [14]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
arr2 = np.array([5, 10, 100]) # (3,) #([[5, 10, 100], [5, 10, 100]])
print(arr1 + arr2)

[[  6  12 103]
 [  9  15 106]]


In [15]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
arr2 = np.array([[100], [200]]) #(2, 1) # ([[100, 100, 100], [200, 200, 200]])
print(arr1 + arr2)

[[101 102 103]
 [204 205 206]]


In [39]:
arr1 = np.array([1, 2, 3]) # (3,)
arr2 = np.array([[4], [5], [6]]) # (3, 1)
print(arr1 + arr2) # (3, 3)

False
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [17]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
arr2 = np.array([1, 2]) # (2,)
# print(arr1 + arr2) # (2, 3)

---
### 행렬 곱셈
- 점곱연산 (Dot Product / 내적)
    - 두 행렬 A, B의 곱셈은 첫 번째 행렬 A의 행과 두 번째 행렬 B의 열 간의 곱셈을 수행한다.
    - 첫 번째 행렬 A의 열의 수와 두 번째 행렬 B의 행의 수가 같아야 한다.
    - 연산 결과의 shape은 (첫 번째 행렬 A의 행수, 두 번째 행렬 B의 열수)이다.

In [18]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(arr1 * arr2)
print(arr1.shape, arr2.shape)

print(np.dot(arr1, arr2))
print(np.dot(arr1, arr2).shape)

[[ 5 12]
 [21 32]]
(2, 2) (2, 2)
[[19 22]
 [43 50]]
(2, 2)


In [19]:
arr3= np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
arr4= np.array([[7, 8], [9, 10], [11, 12]]) # (3, 2)

print(arr3.shape, arr4.shape)
# print(np.dot(arr3, arr4)) -> (2, 3) * (3, 2) => (2, 2)
# print(np.dot(arr4, arr3)) -> (3, 2) * (2, 3) => (3, 3)

(2, 3) (3, 2)


In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)

# # @
# print(arr @ arr) # (2, 3) (2, 3) -> 첫번째 행과, 두번째 열이 맞지 않아서 오류!

# .T : 전치 행렬(행과 열을 뒤집음)
print(arr)
print(arr.T) # arr.T = arr의 전치행렬 (행-열을 교환)
print(arr @ arr.T) # 전치로 인해 행과 열의 갯수가 맞아져서 가능해짐! (2,3) (3,2) => (2, 2)

# matmul() = @ 
print(np.matmul(arr, arr.T))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]
[[14 32]
 [32 77]]


---
### 연산 함수 및 집계 함수

In [21]:
arr_negative = np.array([[-1, -2], [-100, -200]])
arr_float = np.array([[1.234, 5.678], [7.89, 10.123]])
arr = np.arange(1, 7).reshape(2, 3)

In [22]:
# 절대값
print(np.abs(arr_negative))

[[  1   2]
 [100 200]]


In [23]:
# 올림, 반올림
print(np.ceil(arr_float))
print(np.round(arr_float))
print(np.round(arr_float, 2)) # 소수점 N자리 지정할 수 있음음

[[ 2.  6.]
 [ 8. 11.]]
[[ 1.  6.]
 [ 8. 10.]]
[[ 1.23  5.68]
 [ 7.89 10.12]]


In [24]:
arr_float = np.array([[1.234, -5.678], [-7.89, 10.123]])

# 내림 (지정된 수보다 작은 최대 정수)
print(np.floor(arr_float))

# 버림 (절삭)
print(np.trunc(arr_float))

[[ 1. -6.]
 [-8. 10.]]
[[ 1. -5.]
 [-7. 10.]]


In [28]:
# 최대값/최소값
arr = np.arange(1, 7).reshape(2, 3)
print(arr)

print(np.max(arr))
print(np.min(arr))

print(np.max(arr, axis=0)) # 행 기준 (행을 고정하고, 같은 열에서 가장 큰 값)
print(np.min(arr, axis=1)) # 열 기준 (열을 고정하고, 같은 행에서 가장 작은 값)

[[1 2 3]
 [4 5 6]]
6
1
[4 5 6]
[1 4]


In [33]:
# 합계
arr = np.arange(1, 7).reshape(2, 3)

print(arr.sum()) # 21 # axis=None
print(np.sum(arr)) # 21

print(arr.sum(axis=0)) # 행 기준 (행 방향 덧셈) # [5 7 9]
print(arr.sum(axis=1)) # 열 기준 (열 방향 덧셈) # [ 6 15]

[[1 2 3]
 [4 5 6]]
21
21
[5 7 9]
[ 6 15]


In [35]:
# 평균
arr = np.arange(1, 7).reshape(2, 3)
print(arr)

print(arr.mean())    # 3.5
print(np.mean(arr))  # 3.5

print(arr.mean(axis=0)) # [2.5 3.5 4.5]
print(arr.mean(axis=1)) # [2. 5.]

[[1 2 3]
 [4 5 6]]
3.5
3.5
[2.5 3.5 4.5]
[2. 5.]
