In [10]:
!pip install numpy
import numpy as np

### ndarray 정렬

1차원 배열 정렬

In [11]:
arr = np.random.randint(1, 11, 10)
print(arr)

[6 8 4 9 6 6 3 6 5 2]


In [14]:
# np.sort() : 정렬된 ndarray를 반환
arr = np.sort(arr)
print(arr)

[2 3 4 5 6 6 6 6 8 9]


In [15]:
np.sort(arr)[::-1]

array([9, 8, 6, 6, 6, 6, 5, 4, 3, 2], dtype=int32)

---
### 2차원 배열 정렬

In [16]:
arr = np.random.randint(10, size=(3, 4)) # 0 이상 10 미만
print(arr) 

[[5 4 0 5]
 [6 8 7 9]
 [8 8 0 1]]


In [19]:
print(np.sort(arr))             # 기본값 axis=1
print(np.sort(arr, axis=0))     # 행 방향 정렬 (같은 열 안에서 정렬)
print(np.sort(arr, axis=1))     # 열 방향 정렬 (같은 행 안에서 정렬)

[[0 4 5 5]
 [6 7 8 9]
 [0 1 8 8]]
[[5 4 0 1]
 [6 8 0 5]
 [8 8 7 9]]
[[0 4 5 5]
 [6 7 8 9]
 [0 1 8 8]]


In [21]:
print(np.sort(arr, axis=None))        # axis=None 축 무시 (행/열 구분없이 모든 값 정렬)
print(np.sort(arr, axis=None).shape)

[0 0 1 4 5 5 6 7 8 8 8 9]
(12,)


np.argsort()
 - 배열의 값을 정렬했을 때, 각 값의 원래 인덱스를 반환
 - 정렬할 때 어떤 순서로 값을 배치해야 하는 지 알려주는 인덱스를 반환
 - 배열의 값을 정렬한 후, 정렬된 순서에 해당하는 인덱스를 반환
- (= 위치 인덱스 반환!)

In [23]:
arr =np.array([100, 400, 200, 300])

print(np.sort(arr))
print(np.argsort(arr))

[100 200 300 400]
[0 2 3 1]


In [31]:
names = np.array(['리사', '로제', '제니', '지수'])
album_sales = np.array([900, 870, 1000, 670])

print(np.sort(album_sales)[::-1]) # [1000  900  870  670]
print(np.argsort(album_sales)[::-1]) # [2 0 1 3]

sales_desc = np.argsort(album_sales)[::-1]
print(names[sales_desc]) # ['제니' '리사' '로제' '지수']

[1000  900  870  670]
[2 0 1 3]
['제니' '리사' '로제' '지수']


In [33]:
# 2차원 배열에서 argsort
arr = np.array([[2025, 1, 10], [15, 40, 30]])

print(np.argsort(arr))  # 기본 axis 값 = 1
print(np.argsort(arr, axis=0))  # 행 방향 정렬의 순서 (같은 열 안에서 정렬)
print(np.argsort(arr, axis=1))  # 열 방향 정렬의 순서 (같은 행 안에서 정렬)

[[1 2 0]
 [0 2 1]]
[[1 0 0]
 [0 1 1]]
[[1 2 0]
 [0 2 1]]
