### ndarray 병합 및 분할
- ndarray는 고정 길이 배열이므로 크기 변경이 불가하다 == 요소를 추가할 수 없다.

In [1]:
import numpy as np

### ndarray 요소 추가 및 삭제

In [4]:
# insert() : 요소를 추가한 새로운 배열을 반환

arr = np.array([10, 20, 30])

# arr1 = np.append(arr, 40)
arr2 = np.insert(arr, 1, 15) # 1번 자리에 15가 추가 됌 

print(arr)
# print(arr1)
print(arr2 is arr, arr2) # False [10 15 20 30]


[10 20 30]
False [10 15 20 30]


In [9]:
# 2차원 배열에서 insert()
arr = np.arange(1, 13).reshape(3, 4)

print(np.insert(arr, 1, 100))  # axis=None : 1차원 배열로 반환 후 삽입

print(np.insert(arr, 1, [100, 200, 300, 400], axis=0)) # 원본배열, 삽입할 위치 인덱스, 삽입할 요소, axis (axis=0: 행기준)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[  1   2   3   4]
 [100 200 300 400]
 [  5   6   7   8]
 [  9  10  11  12]]


In [12]:
arr = np.arange(1, 13).reshape(3, 4)
# print(arr)

print(np.insert(arr, 1, [100, 200, 300], axis=1))  # axis=1 : 열 기준
print(np.insert(arr, 1, [100], axis=1))
print(np.insert(arr, 1, 100, axis=1))

[[  1 100   2   3   4]
 [  5 200   6   7   8]
 [  9 300  10  11  12]]
[[  1 100   2   3   4]
 [  5 100   6   7   8]
 [  9 100  10  11  12]]
[[  1 100   2   3   4]
 [  5 100   6   7   8]
 [  9 100  10  11  12]]


In [13]:
# delete() : 요소를 삭제한 새로운 배열을 반환

arr = np.arange(1, 15)
print(np.delete(arr, 7))  # 원본배열, 삭제할 요소의 위치 인덱스
print(arr)

[ 1  2  3  4  5  6  7  9 10 11 12 13 14]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
# 2차원 배열에서의 delete()

arr =np.arange(1, 13).reshape(3, 4)
print(arr)

print(np.delete(arr, 1))  # aixs=None : 1차원 배열로 반환 후 삭제

print(np.delete(arr, 1, axis=0))
print(np.delete(arr, 1, axis=1))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]]


---
### ndarray 병합
- np.append()
- np.vstack()
- np.hstack()
- np.concatenate()

In [16]:
arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.arange(13, 25).reshape(3, 4)
print(arr1, arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [18]:
# append()
print(np.append(arr1, arr2))
print(np.append(arr1, arr2, axis=0))
print(np.append(arr1, arr2, axis=1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


In [19]:
# np.vstack() : axis=0 병합과 동일 (행 기준)
print(np.vstack((arr1, arr2)))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [21]:
# np.hstack() : axis=1 병합과 동일 (열 기준)
print(np.hstack([arr1, arr2]))


[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


In [24]:
# np.concatenate()
print(np.concatenate((arr1, arr2)))
print(np.concatenate((arr1, arr2), axis=0))
print(np.concatenate((arr1, arr2), axis=1))
print(np.concatenate((arr1, arr2), axis=None))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
