### ndarray 형태변경

In [1]:
import numpy as np

In [7]:
# reshape()
# 요소의 갯수가 맞는 shape으로 변형 가능

arr = np.arange(12)
print(arr.ndim, arr) # ndim : 깊이를 나타내 줌(차원)

arr = arr.reshape(3, 4)
# arr = arr.reshape(2, 7) # 요소가 14개라는 범위를 넘어서서 error 나는 것 -> 요소의 갯수를 바꿀 순 없음
print(arr.ndim, arr.shape)
print(arr)

arr = arr.reshape(2, 2, 3)
# arr = arr.reshape(2, 2, 2) -> 똑같이 요소 갯수 맞춰야만 가능!
print(arr.ndim, arr.shape)
print(arr)

1 [ 0  1  2  3  4  5  6  7  8  9 10 11]
2 (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
3 (2, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [11]:
# reshape() -> -1
arr = arr.reshape(-1)  # 1차원으로 처리
print(arr)

arr = arr.reshape(4, -1)  # 행의 갯수를 정해주면, 열의 갯수는 알아서 함
arr = arr.reshape(-1, 4)  # 열의 갯수를 정해주면, 행의 갯수는 알아서 함
# -1 은 자동해주는 값으로 생각하면 됌
arr = arr.reshape(-1, 5)  # 요소의 갯수가 맞아야 shape 변형 가능 
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


ValueError: cannot reshape array of size 12 into shape (5)

In [12]:
# np.ravel() : 1차원 변환
arr = np.arange(50).reshape(5, 10)
print(arr)
print(np.ravel(arr))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [16]:
# np.expand_dims() : 가진 요소를 가지고 차원 수를 늘림.
arr_1d = np.arange(10)
print(arr_1d.shape, arr_1d)

print(np.expand_dims(arr_1d, axis=0))
print(np.expand_dims(arr_1d, axis=1))
print(np.expand_dims(arr_1d, axis=0).shape)
print(np.expand_dims(arr_1d, axis=1).shape)

(10,) [0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(1, 10)
(10, 1)


In [19]:
arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d.shape, arr_2d)

print(np.expand_dims(arr_2d, axis=0))
print(np.expand_dims(arr_2d, axis=1))
print(np.expand_dims(arr_2d, axis=2))
print(np.expand_dims(arr_2d, axis=0).shape)
print(np.expand_dims(arr_2d, axis=1).shape)
print(np.expand_dims(arr_2d, axis=2).shape)

(2, 2) [[1 2]
 [3 4]]
[[[1 2]
  [3 4]]]
[[[1 2]]

 [[3 4]]]
[[[1]
  [2]]

 [[3]
  [4]]]
(1, 2, 2)
(2, 1, 2)
(2, 2, 1)


In [22]:
# np.squeeze() : 차원의 값이 1일 때 제거
arr = np.array([[1, 2]])
print(arr.shape) # (1, 2)

arr2 = np.squeeze(arr)
print(arr2.shape) # (2,)

arr2 = np.squeeze(arr, axis=0)
# arr2 = np.squeeze(arr, axis=1) # Error 남, 1차원만 squeeze 가능함 
print(arr2.shape) # (2,)

(1, 2)
(2,)
(2,)
