In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

iris_data = load_iris()
iris_data.keys()
# iris_data.target_names
# iris_data.feature_names


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [21]:
print(iris_data.data) #  input 데이터 (특성 데이터)
print(iris_data.feature_names) # 특성명

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [22]:
print(iris_data.target) # 숫자로 인코딩된 label 데이터 (정답 데이터)
print(iris_data.target_names) # label 명

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


## 최근접 이웃 분류 모델로 훈련/평가 해보기

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [32]:
# # 데이터 전처리 -> 내 풀이 (라벨데이터에서 오류...)
# # 1. 입력-라벨 데이터
# train_input = iris_data.feature_names
# train_label = iris_data.target_names

# # 2. 훈련-테스트 데이터
# train_input, test_input, train_label, test_label = train_test_split(train_input, train_label, test_size=0.2, random_state=42)

# # 3. 정규화
# standard_scaler = StandardScaler()
# standard_scaler.fit(train_input)
# train_scaled = standard_scaler.transform(train_input)
# test_scaled = standard_scaler.transform(test_input)


In [34]:
# 데이터 전처리 -> 선생님 풀이이
# 1. 입력-라벨 데이터 (O)
# 이미 위에서 했음. 고로 패스

# 2. 훈련-테스트 데이터
from sklearn.model_selection import train_test_split
train_input, test_input, train_label, test_label = train_test_split(iris_data.data, iris_data.target, test_size=.25, random_state=42)

train_input.shape, test_input.shape, train_label.shape, test_label.shape


# 3. 정규화
scaler = StandardScaler()
scaler.fit(train_input)
train_scaled = scaler.transform(train_input)
test_scaled = scaler.transform(test_input)



In [35]:
# 훈련
kn = KNeighborsClassifier(n_neighbors=7)
kn.fit(train_scaled, train_label)


KNeighborsClassifier(n_neighbors=7)

In [36]:
# 평가
kn.score(test_scaled, test_label)

1.0

In [37]:
# 평가 : accuracy_score
from sklearn.metrics import accuracy_score

pred = kn.predict(test_scaled)

accuracy_score(test_label, pred)

1.0