In [1]:
import numpy as np

### 1 실습

In [2]:
arr = np.array([50, 10, 30, 40, 20])

print(np.sort(arr))
print(np.sort(arr)[::-1])

[10 20 30 40 50]
[50 40 30 20 10]


In [3]:
arr2d = np.array([[8, 3, 5], [2, 9, 1]])

print(np.sort(arr2d, axis=0))
print(np.sort(arr2d, axis=1))

[[2 3 1]
 [8 9 5]]
[[3 5 8]
 [1 2 9]]


In [9]:
arr = np.array([15, 10, 20])
print(np.argsort(arr))

arr2 = np.argsort(arr)
print(arr[arr2])

[1 0 2]
[10 15 20]
